description: Iowa gross income adjustments sources.
values:
  2021-01-01:
    - pension_contributions
    - self_employment_tax_ald_person
    - alimony_expense
    - ia_pension_exclusion

metadata:
  unit: variable
  label: Iowa gross income adjustments sources
  reference:
  - title: 2021 IA1040 Iowa Income Tax Return, Lines 16-24
    href: https://tax.iowa.gov/sites/default/files/2022-01/IA1040%2841-001%29.pdf#page=1
  - title: 2021 IA1040 Income Tax Return instructions
    href: https://tax.iowa.gov/sites/default/files/2023-01/2021%20Expanded%20Instructions_010323.pdf#page=23
  - title: 2022 IA1040 Iowa Income Tax Return, Lines 16-24
    href: https://tax.iowa.gov/sites/default/files/2023-01/2022IA1040%2841001%29.pdf#page=1
  - title: 2022 IA1040 Income Tax Return instructions
    href: https://tax.iowa.gov/sites/default/files/2023-03/2022%20Expanded%20Instructions_022023.pdf#page=23
