name: fiscalsim-us-dev
channels:
- conda-forge
dependencies:
  - python>=3.10,<3.12
  - matplotlib
  - sphinx>=3.5.4
  - sphinx-argparse
  - sphinxcontrib-bibtex>=2.0.0
  - sphinx-math-dollar
  - pydata-sphinx-theme
  - jupyter-book>=0.11.3
  - jupyter
  - pip
