description: Wisconsin exemption includes this base amount.
metadata:
  period: year
  unit: currency-USD
  reference:
    - title: Legislative Fiscal Bureau paper on WI income tax 
      href: https://docs.legis.wisconsin.gov/misc/lfb/informational_papers/january_2023/0002_individual_income_tax_informational_paper_2.pdf
values:
  2001-01-01: 700
