description: Minnesota adds these variables to US AGI when computing its taxable income.
values:
  2021-01-01:
    - c05700  # lump-sum distributions from federal Form 4972

metadata:
  unit: variable
  label: MN additions to US AGI
  reference:
  - title: 2021 MN Schedule M1M, Income Additions and Subtractions
    href: https://www.taxformfinder.org/forms/2021/2021-minnesota-form-m1m.pdf
  - title: 2022 MN Schedule M1M, Income Additions and Subtractions
    href: https://www.revenue.state.mn.us/sites/default/files/2023-01/m1m_22.pdf
