title: FiscalSim US documentation
author: Center for Growth and Opportunity at Utah State University
copyright: "2023"

execute:
  execute_notebooks: force
  timeout: -1

repository:
  url: https://github.com/TheCGO/fiscalsim-us
  branch: main
  path_to_book: docs

sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_theme: furo
    pygments_style: default
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinxarg.ext"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.napoleon"
    - "sphinx.ext.mathjax"
