name: Check that docs build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          python-version: "3.9"
      - name: Install package
        run: make install

      - name: Build documentation  # Build Jupyter Book
        run: make documentation
