name: Push
on:
  push:
    branches: [master]
jobs:
  Lint:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'TheCGO/fiscalsim-us')
      && (github.event.head_commit.message == 'Update FiscalSim-US')
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  versioning:
    name: Update versioning
    if: |
      (github.repository == 'TheCGO/fiscalsim-us')
      && !(github.event.head_commit.message == 'Update FiscalSim-US')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.THECGO_GITHUB }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Build changelog
        run: pip install yaml-changelog && make changelog
      - name: Preview changelog update
        run: ".github/get-changelog-diff.sh"
      - name: Update changelog
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          committer_name: Github Actions[bot]
          author_name: Github Actions[bot]
          message: Update FiscalSim-US
  Test:
    runs-on: ${{ matrix.os }}
    if: |
      (github.repository == 'TheCGO/fiscalsim-us')
      && (github.event.head_commit.message == 'Update FiscalSim-US')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install package
        run: make install
      - name: Run tests
        run: make test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Not required for public repos
          files: ./coverage.xml  # optional
          flags: unittests  # optional
          name: codecov-umbrella  # optional
          fail_ci_if_error: true  # optional (default = false)
          verbose: true  # optional (default = false)
      - name: Test documentation builds
        if: matrix.os == 'ubuntu-latest'
        run: make documentation
