name: Push
on:
  push:
    branches: [main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'TheCGO/fiscalsim-us')
      && (github.event.head_commit.message == 'Update FiscalSim US')
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  Test:
    runs-on: ${{ matrix.os }}
    if: |
      (github.repository == 'TheCGO/fiscalsim-us')
      && (github.event.head_commit.message == 'Update FiscalSim US')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install package
        run: make install
      - name: Run tests
        run: make test
      - uses: codecov/codecov-action@v3
      - name: Test documentation builds
        if: matrix.os == 'ubuntu-latest'
        run: make documentation
